name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # macOS
          - { goos: darwin, goarch: arm64, output: flow-darwin-arm64 }
          - { goos: darwin, goarch: amd64, goamd64: v1, output: flow-darwin-amd64-compatible }
          - { goos: darwin, goarch: amd64, goamd64: v3, output: flow-darwin-amd64 }

          # Linux
          - { goos: linux, goarch: '386', output: flow-linux-386 }
          - { goos: linux, goarch: amd64, goamd64: v1, output: flow-linux-amd64-compatible }
          - { goos: linux, goarch: amd64, goamd64: v3, output: flow-linux-amd64 }
          - { goos: linux, goarch: arm64, output: flow-linux-arm64 }
          - { goos: linux, goarch: arm, goarm: '5', output: flow-linux-armv5 }
          - { goos: linux, goarch: arm, goarm: '6', output: flow-linux-armv6 }
          - { goos: linux, goarch: arm, goarm: '7', output: flow-linux-armv7 }
          - { goos: linux, goarch: mips, gomips: hardfloat, output: flow-linux-mips-hardfloat }
          - { goos: linux, goarch: mips, gomips: softfloat, output: flow-linux-mips-softfloat }
          - { goos: linux, goarch: mipsle, gomips: hardfloat, output: flow-linux-mipsle-hardfloat }
          - { goos: linux, goarch: mipsle, gomips: softfloat, output: flow-linux-mipsle-softfloat }
          - { goos: linux, goarch: mips64, output: flow-linux-mips64 }
          - { goos: linux, goarch: mips64le, output: flow-linux-mips64le }
          - { goos: linux, goarch: loong64, output: flow-linux-loong64-abi1, abi: '1' }
          - { goos: linux, goarch: loong64, output: flow-linux-loong64-abi2, abi: '2' }
          - { goos: linux, goarch: riscv64, output: flow-linux-riscv64 }
          - { goos: linux, goarch: s390x, output: flow-linux-s390x }

          # Windows
          - { goos: windows, goarch: '386', output: flow-windows-386 }
          - { goos: windows, goarch: amd64, goamd64: v1, output: flow-windows-amd64-compatible }
          - { goos: windows, goarch: amd64, goamd64: v3, output: flow-windows-amd64 }
          - { goos: windows, goarch: arm, goarm: '7', output: flow-windows-armv7 }
          - { goos: windows, goarch: arm64, output: flow-windows-arm64 }

          # FreeBSD
          - { goos: freebsd, goarch: '386', output: flow-freebsd-386 }
          - { goos: freebsd, goarch: amd64, goamd64: v1, output: flow-freebsd-amd64-compatible }
          - { goos: freebsd, goarch: amd64, goamd64: v3, output: flow-freebsd-amd64 }
          - { goos: freebsd, goarch: arm64, output: flow-freebsd-arm64 }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 'latest'

      - name: Build the application
        run: |
          output_file="${{ matrix.output }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $output_file ./path/to/your/source

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}  # 使用输入的标签名
          files: |
            flow-darwin-arm64
            flow-darwin-amd64-compatible
            flow-darwin-amd64
            flow-linux-386
            flow-linux-amd64-compatible
            flow-linux-amd64
            flow-linux-arm64
            flow-linux-armv5
            flow-linux-armv6
            flow-linux-armv7
            flow-linux-mips-hardfloat
            flow-linux-mips-softfloat
            flow-linux-mipsle-hardfloat
            flow-linux-mipsle-softfloat
            flow-linux-mips64
            flow-linux-mips64le
            flow-linux-loong64-abi1
            flow-linux-loong64-abi2
            flow-linux-riscv64
            flow-linux-s390x
            flow-windows-386
            flow-windows-amd64-compatible
            flow-windows-amd64
            flow-windows-armv7
            flow-windows-arm64
            flow-freebsd-386
            flow-freebsd-amd64-compatible
            flow-freebsd-amd64
            flow-freebsd-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
